# Generated by Django 5.1 on 2024-09-30 17:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, max_length=200, null=True)),
                ('place', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('day', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('gphotos', models.CharField(max_length=700, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_photos/')),
            ],
        ),
    ]
