# Generated by Django 5.1 on 2024-11-12 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Pages',
        ),
    ]
